BOG/Models/Sale.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BOG.Models
{
    public class Sale
    {
        // Primary Key
        public long Id { get; set; }

        public int ConsultantId { get; set; }

        [ForeignKey("ConsultantId")]
        public virtual Consultant Consultant { get; set; }
        
        public DateTime CreatedAt { get; set; }

        public List<SaleDetail> SaleDetails { get; set; }
    }
}

BOG/Controllers/SaleDetailsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BOG.Constants.Filtering;
using BOG.Constants.Paging;
using BOG.DAL.Implementation;
using BOG.Helper;
using BOG.Models;
using PagedList;

namespace BOG.Controllers
{
    public class SaleDetailsController : Controller
    {
        private readonly Bog _db = new Bog();

        // GET: SaleDetails
        public ActionResult Index(string sortOrder,long? searchId, string searchName, long? searchSaleId, long? searchProductId, int? searchAmount, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentFilterId = searchId;
            ViewBag.CurrentFilterName = searchName;
            ViewBag.CurrentFilterProductId = searchProductId;
            ViewBag.CurrentFilterSaleId = searchSaleId;
            ViewBag.CurrentFilterAmount = searchAmount;
            ViewBag.IdSortParam = string.IsNullOrEmpty(sortOrder) ? FilteringNames.IdDesc : "";
            ViewBag.NameSortParam = sortOrder == FilteringNames.Name ? FilteringNames.NameDesc : FilteringNames.Name;
            ViewBag.ProductIdSortParam = sortOrder == FilteringNames.ProductId ? FilteringNames.ProductIdDesc : FilteringNames.ProductId;
            ViewBag.SaleIdSortParam = sortOrder == FilteringNames.SaleId ? FilteringNames.SaleIdDesc : FilteringNames.SaleId;
            ViewBag.AmountSortParam = sortOrder == FilteringNames.Amount ? FilteringNames.AmountDesc : FilteringNames.Amount;
            var saleDetails = _db.SaleDetails.ToList();
            if (searchId.HasValue)
            {
                saleDetails = saleDetails.Where(s => s.Id == searchId).ToList();
            }
            if (!string.IsNullOrEmpty(searchName))
            {
                saleDetails = saleDetails.Where(s => s.Product.Name.Contains(searchName)).ToList();
            }
            if (searchProductId.HasValue)
            {
                saleDetails = saleDetails.Where(s => s.ProductId == searchProductId).ToList();
            }
            if (searchSaleId.HasValue)
            {
                saleDetails = saleDetails.Where(s => s.SaleId == searchSaleId).ToList();
            }
            if (searchAmount.HasValue)
            {
                saleDetails = saleDetails.Where(s => s.Amount == searchAmount).ToList();
            }
            switch (sortOrder)
            {
                case FilteringNames.IdDesc:
                    saleDetails = saleDetails.OrderByDescending(s => s.Id).ToList();
                    break;
                case FilteringNames.SaleIdDesc:
                    saleDetails = saleDetails.OrderByDescending(s => s.SaleId).ToList();
                    break;
                case FilteringNames.ProductIdDesc:
                    saleDetails = saleDetails.OrderByDescending(s => s.ProductId).ToList();
                    break;
                case FilteringNames.NameDesc:
                    saleDetails = saleDetails.OrderByDescending(s => s.Product.Name).ToList();
                    break;
                case FilteringNames.AmountDesc:
                    saleDetails = saleDetails.OrderByDescending(s => s.Amount).ToList();
                    break;
                case FilteringNames.SaleId:
                    saleDetails = saleDetails.OrderBy(s => s.SaleId).ToList();
                    break;
                case FilteringNames.ProductId:
                    saleDetails = saleDetails.OrderBy(s => s.ProductId).ToList();
                    break;
                case FilteringNames.Name:
                    saleDetails = saleDetails.OrderBy(s => s.Product.Name).ToList();
                    break;
                case FilteringNames.Amount:
                    saleDetails = saleDetails.OrderBy(s => s.Amount).ToList();
                    break;
                default:
                    saleDetails = saleDetails.OrderBy(s => s.Id).ToList();
                    break;
            }
            var pagedData = saleDetails.ToPagedList(PageFormatter.GetValidPage(page), Paging.PageSize);
            if (!pagedData.Any() && PageFormatter.GetValidPage(page) != 1)
            {
                return View(saleDetails.ToPagedList(1, Paging.PageSize));
            }
            return View(pagedData);
        }

        // GET: SaleDetails/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var saleDetail = await _db.SaleDetails.FindAsync(id);
            if (saleDetail == null)
            {
                return HttpNotFound();
            }
            return View(saleDetail);
        }

        // GET: SaleDetails/Create
        public ActionResult Create()
        {
            ViewBag.SaleIds = _db.Sales.ToListAsync().Result;
            ViewBag.ProductIds = _db.Products.ToListAsync().Result;
            return View();
        }

        // POST: SaleDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,SaleId,ProductId,Amount")] SaleDetail saleDetail)
        {
            if (saleDetail.Amount <= 0)
            {
                throw new Exception("Amount Is Equal Or Less Than Zero");
            }
            if (!ModelState.IsValid)
            {
                return View(saleDetail);
            }
            _db.SaleDetails.Add(saleDetail);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");

        }

        // GET: SaleDetails/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var saleDetail = await _db.SaleDetails.FindAsync(id);
            if (saleDetail == null)
            {
                return HttpNotFound();
            }
            return View(saleDetail);
        }

        // POST: SaleDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,SaleId,ProductId,Amount")] SaleDetail saleDetail)
        {
            if (saleDetail.Amount <= 0)
            {
                throw new Exception("Amount Is Equal Or Less Than Zero");
            }
            if (!ModelState.IsValid)
            {
                return View(saleDetail);
            }
            _db.Entry(saleDetail).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: SaleDetails/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var saleDetail = await _db.SaleDetails.FindAsync(id);
            if (saleDetail == null)
            {
                return HttpNotFound();
            }
            return View(saleDetail);
        }

        // POST: SaleDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            _db.SaleDetails.Remove(await _db.SaleDetails.FindAsync(id) ?? throw new InvalidOperationException());
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BOG/Controllers/SalesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BOG.Constants.Filtering;
using BOG.Constants.Paging;
using BOG.DAL.Implementation;
using BOG.Helper;
using BOG.Models;
using PagedList;

namespace BOG.Controllers
{
    public class SalesController : Controller
    {
        private readonly Bog _db = new Bog();

        // GET: Sales
        public ActionResult Index(string sortOrder, int? searchId, string searchName, string searchLastName, int? searchConsultantId, DateTime? searchCreatedAt, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentFilterId = searchId;
            ViewBag.CurrentFilterName = searchName;
            ViewBag.CurrentFilterLastName = searchLastName;
            ViewBag.CurrentFilterConsultantId = searchConsultantId;
            ViewBag.CurrentFilterCreatedAt = searchCreatedAt;
            ViewBag.IdSortParam = string.IsNullOrEmpty(sortOrder) ? FilteringNames.IdDesc : "";
            ViewBag.NameSortParam = sortOrder == FilteringNames.Name ? FilteringNames.NameDesc : FilteringNames.Name;
            ViewBag.LastNameSortParam = sortOrder == FilteringNames.LastName ? FilteringNames.LastNameDesc : FilteringNames.LastName;
            ViewBag.CreatedAtSortParam = sortOrder == FilteringNames.CreatedAt ? FilteringNames.CreatedAtDesc : FilteringNames.CreatedAt;
            ViewBag.ConsultantIdSortParam = sortOrder == FilteringNames.ConsultantId ? FilteringNames.ConsultantIdDesc : FilteringNames.ConsultantId;
            var sales = _db.Sales.ToList();
            if (searchId.HasValue)
            {
                sales = sales.Where(s => s.Id == searchId).ToList();
            }
            if (!string.IsNullOrEmpty(searchName))
            {
                sales = sales.Where(s => s.Consultant.Name.Contains(searchName)).ToList();
            }
            if (!string.IsNullOrEmpty(searchLastName))
            {
                sales = sales.Where(s => s.Consultant.LastName.Contains(searchLastName)).ToList();
            }
            if (searchConsultantId.HasValue)
            {
                sales = sales.Where(s => s.ConsultantId == searchConsultantId.Value).ToList();
            }
            if (searchCreatedAt != null)
            {
                sales = sales.Where(s => s.CreatedAt.Day == searchCreatedAt.Value.Day
                                                     && s.CreatedAt.Month == searchCreatedAt.Value.Month
                                                     && s.CreatedAt.Year == searchCreatedAt.Value.Year).ToList();
            }
            switch (sortOrder)
            {
                case FilteringNames.IdDesc:
                    sales = sales.OrderByDescending(s => s.Id).ToList();
                    break;
                case FilteringNames.LastNameDesc:
                    sales = sales.OrderByDescending(s => s.Consultant.LastName).ToList();
                    break;
                case FilteringNames.NameDesc:
                    sales = sales.OrderByDescending(s => s.Consultant.Name).ToList();
                    break;
                case FilteringNames.ConsultantIdDesc:
                    sales = sales.OrderByDescending(s => s.ConsultantId).ToList();
                    break;
                case FilteringNames.CreatedAtDesc:
                    sales = sales.OrderByDescending(s => s.CreatedAt).ToList();
                    break;
                case FilteringNames.Name:
                    sales = sales.OrderBy(s => s.Consultant.Name).ToList();
                    break;
                case FilteringNames.LastName:
                    sales = sales.OrderBy(s => s.Consultant.LastName).ToList();
                    break;
                case FilteringNames.CreatedAt:
                    sales = sales.OrderBy(s => s.CreatedAt).ToList();
                    break;
                case FilteringNames.ConsultantId:
                    sales = sales.OrderBy(s => s.ConsultantId).ToList();
                    break;
                default:
                    sales = sales.OrderBy(s => s.Id).ToList();
                    break;
            }
            var pagedData = sales.ToPagedList(PageFormatter.GetValidPage(page), Paging.PageSize);
            if (!pagedData.Any() && PageFormatter.GetValidPage(page) != 1)
            {
                return View(sales.ToPagedList(1, Paging.PageSize));
            }
            return View(pagedData);
        }

        // GET: Sales/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sale = await _db.Sales.FindAsync(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            sale.SaleDetails = _db.SaleDetails.Where(x => x.SaleId == id.Value).ToList();
            return View(sale);
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            ViewBag.ConsultantIds = _db.Consultants.ToListAsync().Result;
            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,ConsultantId,CreatedAt")] Sale sale)
        {
            if (!ModelState.IsValid)
            {
                return View(sale);
            }
            sale.CreatedAt = DateTime.Now;
            _db.Sales.Add(sale);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Sales/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sale = await _db.Sales.FindAsync(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,ConsultantId,CreatedAt")] Sale sale)
        {
            if (!ModelState.IsValid)
            {
                return View(sale);
            }
            _db.Entry(sale).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Sales/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sale = await _db.Sales.FindAsync(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            _db.Sales.Remove(await _db.Sales.FindAsync(id) ?? throw new InvalidOperationException());
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BOG/Views/Sales/Create.cshtml
@model BOG.Models.Sale

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ConsultantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("consultantId", new SelectList(ViewBag.ConsultantIds, "Id", "Id"), null, new {@class="form-control"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BOG/Views/Sales/Delete.cshtml
@model BOG.Models.Sale

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sale</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ConsultantId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsultantId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BOG/Views/Sales/Details.cshtml
@model BOG.Models.Sale

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Sale</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsultantId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsultantId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consultant.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consultant.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consultant.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consultant.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h2>SaleDetails</h2>


<table class="table">
    @if (Model.SaleDetails.Count > 0)
    {
    <tr>
        <th>
            @Html.DisplayNameFor(model => Model.SaleDetails.First().SaleId)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.SaleDetails.First().ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.SaleDetails.First().Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => Model.SaleDetails.First().Amount)
        </th>
        <th></th>
    </tr>
    }

    @foreach (var item in Model.SaleDetails)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SaleId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Product.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "SaleDetails", new { id = item.Id }, null) |
                @Html.ActionLink("Details", "Details", "SaleDetails", new { id = item.Id }, null) |
                @Html.ActionLink("Delete", "Delete", "SaleDetails", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>

BOG/Views/Sales/Edit.cshtml
@model BOG.Models.Sale

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Sale</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ConsultantId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConsultantId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConsultantId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BOG/Views/Sales/Index.cshtml
@model PagedList.IPagedList<BOG.Models.Sale>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}
<br>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        @Html.TextBox("searchId", ViewBag.CurrentFilterId as int?) - Find by Id
    </p>
    <p>
        @Html.TextBox("searchName", ViewBag.CurrentFilterName as string) - Find by Consultant Name
    </p>
    <p>
        @Html.TextBox("searchLastName", ViewBag.CurrentFilterLastName as string) - Find by Consultant Last Name
    </p>
    <p>
        @Html.TextBox("searchConsultantId", ViewBag.CurrentFilterConsultantId as int?) - Find by Consultant Id
    </p>
    <p>
        @Html.TextBox("searchCreatedAt", ViewBag.CurrentFilterCreatedAt as DateTime?) - Find by CreatedAt
    </p>
    <input type="submit" value="Filter" />
}
<br>
@using (Html.BeginForm())
{
    <input type="submit" value="Reset" />
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParam })
        </th>
        <th>
            @Html.ActionLink("ConsultantId", "Index", new { sortOrder = ViewBag.ConsultantIdSortParam })
        </th>
        <th>
            @Html.ActionLink("Consultant Name", "Index", new { sortOrder = ViewBag.NameSortParam })
        </th>
        <th>
            @Html.ActionLink("Consultant LastName", "Index", new { sortOrder = ViewBag.LastNameSortParam })
        </th>
        <th>
            @Html.ActionLink("CreatedAt", "Index", new { sortOrder = ViewBag.CreatedAtSortParam })
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsultantId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Consultant.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Consultant.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { sortOrder = ViewBag.CurrentSort,
        searchName = ViewBag.CurrentFilterName,
        searchLastName = ViewBag.CurrentFilterLastName,
        searchConsultantId = ViewBag.CurrentFilterConsultantId,
        searchCreatedAt = ViewBag.CurrentFilterCreatedAt,
        page }))