BOG/Controllers/SaleDetailSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BOG.Constants.Filtering;
using BOG.Constants.Paging;
using BOG.DAL.Implementation;
using BOG.DAL.Interface;
using BOG.Helper;
using BOG.Models.SearchModels;
using PagedList;

namespace BOG.Controllers
{
    public class SaleDetailSearchController : Controller
    {
        private readonly IConsultantDal _consultantDal = IoC.Instance.GetInstance<ConsultantDal>();

        // GET: SaleInfoByProductPrice
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetSaleInfoByProductPrice(string sortOrder, int? searchConsultantId, string searchConsultantName, string searchConsultantLastName, long? searchConsultantPersonalid, long? searchSaleId, int? searchProductAmount, decimal? minPrice, decimal? maxPrice, DateTime? startDate, DateTime? endDate, int? page)
        {
            if (!minPrice.HasValue || !maxPrice.HasValue || !startDate.HasValue || !endDate.HasValue)
            {
                return View(new List<SaleInfoByProductPrice>().ToPagedList(PageFormatter.GetValidPage(page), Paging.PageSize));
            }
            ModifySort(sortOrder);
            ModifySearchingParameter(startDate, endDate, minPrice: minPrice, maxPrice : maxPrice);
            ViewBag.CurrentSort = sortOrder;

            ModifyConsultantFiltering(searchConsultantId, searchConsultantName, searchConsultantLastName, searchConsultantPersonalid);
            ViewBag.CurrentFilterProductAmount = searchProductAmount;
            ViewBag.CurrentFilterSaleId = searchSaleId;

            var salesInfoByProductPrices = _consultantDal.GetSaleInfoProductPrice(minPrice.Value, maxPrice.Value, startDate.Value, endDate.Value);
            if (searchConsultantId.HasValue)
            {
                salesInfoByProductPrices = salesInfoByProductPrices.Where(s => s.ConsultantId == searchConsultantId).ToList();
            }
            if (!string.IsNullOrEmpty(searchConsultantName))
            {
                salesInfoByProductPrices = salesInfoByProductPrices.Where(s => s.ConsultantName.Contains(searchConsultantName)).ToList();
            }
            if (!string.IsNullOrEmpty(searchConsultantLastName))
            {
                salesInfoByProductPrices = salesInfoByProductPrices.Where(s => s.ConsultantLastName.Contains(searchConsultantLastName)).ToList();
            }
            if (searchConsultantPersonalid.HasValue)
            {
                salesInfoByProductPrices = salesInfoByProductPrices.Where(s => s.ConsultantPersonalId == searchConsultantPersonalid).ToList();
            }
            if (searchProductAmount.HasValue)
            {
                salesInfoByProductPrices = salesInfoByProductPrices.Where(s => s.ProductAmount == searchProductAmount).ToList();
            }
            if (searchSaleId.HasValue)
            {
                salesInfoByProductPrices = salesInfoByProductPrices.Where(s => s.SaleId == searchSaleId).ToList();
            }
            switch (sortOrder)
            {
                case FilteringNames.ConsultantIdDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.ConsultantId).ToList();
                    break;
                case FilteringNames.LastNameDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.ConsultantLastName).ToList();
                    break;
                case FilteringNames.NameDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.ConsultantName).ToList();
                    break;
                case FilteringNames.SaleDateDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.SalesDate).ToList();
                    break;
                case FilteringNames.PersonalIdDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.ConsultantPersonalId).ToList();
                    break;
                case FilteringNames.AmountDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.ProductAmount).ToList();
                    break;
                case FilteringNames.SaleIdDesc:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderByDescending(s => s.SaleId).ToList();
                    break;
                case FilteringNames.LastName:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.ConsultantLastName).ToList();
                    break;
                case FilteringNames.Name:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.ConsultantName).ToList();
                    break;
                case FilteringNames.SaleDate:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.SalesDate).ToList();
                    break;
                case FilteringNames.PersonalId:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.ConsultantPersonalId).ToList();
                    break;
                case FilteringNames.Amount:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.ProductAmount).ToList();
                    break;
                case FilteringNames.SaleId:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.SaleId).ToList();
                    break;
                default:
                    salesInfoByProductPrices = salesInfoByProductPrices.OrderBy(s => s.ConsultantId).ToList();
                    break;
            }
            var pagedData = salesInfoByProductPrices.ToPagedList(PageFormatter.GetValidPage(page), Paging.PageSize);
            if (!pagedData.Any() && PageFormatter.GetValidPage(page) != 1)
            {
                return View(salesInfoByProductPrices.ToPagedList(1, Paging.PageSize));
            }
            return View(pagedData);
        }

        public ActionResult GetSaleInfoByConsultant(string sortOrder, int? searchConsultantId, string searchConsultantName, string searchConsultantLastName, long? searchConsultantPersonalid, long? searchSaleId, int? searchProductAmount, int? searchTotalPrice, DateTime? startDate, DateTime? endDate, int? page)
        {
            if (!startDate.HasValue || !endDate.HasValue)
            {
                return View(new List<SaleInfoByConsultant>().ToPagedList(PageFormatter.GetValidPage(page), Paging.PageSize));
            }
            ModifySort(sortOrder);
            ModifySearchingParameter(startDate, endDate);
            ViewBag.CurrentSort = sortOrder;

            ModifyConsultantFiltering(searchConsultantId, searchConsultantName, searchConsultantLastName, searchConsultantPersonalid);
            ViewBag.CurrentFilterSaleId = searchSaleId;
            ViewBag.CurrentFilterProductAmount = searchProductAmount;
            ViewBag.CurrentFilterTotalPrice = searchTotalPrice;

            var saleInfos = _consultantDal.GetSaleInfoByConsultants(startDate.Value, endDate.Value);
            if (searchConsultantId.HasValue)
            {
                saleInfos = saleInfos.Where(s => s.ConsultantId == searchConsultantId).ToList();
            }
            if (!string.IsNullOrEmpty(searchConsultantName))
            {
                saleInfos = saleInfos.Where(s => s.ConsultantName.Contains(searchConsultantName)).ToList();
            }
            if (!string.IsNullOrEmpty(searchConsultantLastName))
            {
                saleInfos = saleInfos.Where(s => s.ConsultantLastName.Contains(searchConsultantLastName)).ToList();
            }
            if (searchConsultantPersonalid.HasValue)
            {
                saleInfos = saleInfos.Where(s => s.ConsultantPersonalId == searchConsultantPersonalid).ToList();
            }
            if (searchSaleId.HasValue)
            {
                saleInfos = saleInfos.Where(s => s.SaleId == searchSaleId).ToList();
            }
            if (searchProductAmount.HasValue)
            {
                saleInfos = saleInfos.Where(s => s.ProductAmount == searchProductAmount).ToList();
            }
            if (searchTotalPrice.HasValue)
            {
                saleInfos = saleInfos.Where(s => s.TotalPrice == searchTotalPrice).ToList();
            }
            switch (sortOrder)
            {
                case FilteringNames.ConsultantIdDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.ConsultantId).ToList();
                    break;
                case FilteringNames.SaleIdDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.SaleId).ToList();
                    break;
                case FilteringNames.TotalPriceDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.TotalPrice).ToList();
                    break;
                case FilteringNames.LastNameDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.ConsultantLastName).ToList();
                    break;
                case FilteringNames.NameDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.ConsultantName).ToList();
                    break;
                case FilteringNames.SaleDateDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.SalesDate).ToList();
                    break;
                case FilteringNames.PersonalIdDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.ConsultantPersonalId).ToList();
                    break;
                case FilteringNames.AmountDesc:
                    saleInfos = saleInfos.OrderByDescending(s => s.ProductAmount).ToList();
                    break;
                case FilteringNames.LastName:

BOG/Views/SaleDetailSearch/GetConsultantsSalesCount.cshtml
@model PagedList.IPagedList<BOG.Models.SearchModels.ConsultantSalesCount>
@using PagedList.Mvc;

@{
    ViewBag.Title = "SaleInfoByConsultant";
}

<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("GetSaleInfoByConsultant I", "GetSaleInfoByConsultant", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetSaleInfoByProductPrice II", "GetSaleInfoByProductPrice", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetFrequentlySaledProducts III", "GetFrequentlySaledProducts", "SaleDetailSearch")</li>
        <li class="active">@Html.ActionLink("GetConsultantsSalesCount IV", "GetConsultantsSalesCount", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetProfitableProducts V", "GetProfitableProducts", "SaleDetailSearch")</li>
    </ul>
</nav>

@using (Html.BeginForm("GetConsultantsSalesCount", "SaleDetailSearch"))
{
    <p>
        @Html.TextBox("startDate", ViewBag.SearchParameterStartDate as DateTime?, new { type = "date" }) - Filter From StartDate
    </p>
    <p>
        @Html.TextBox("endDate", ViewBag.SearchParameterEndDate as DateTime?, new { type = "date" }) -  Filter To EndDate
    </p>
    <p>
        -------------------------------------------
    </p>
    <p>
        @Html.TextBox("searchConsultantId", ViewBag.CurrentFilterConsultantId as int?) - Find by Consultant Id
    </p>
    <p>
        @Html.TextBox("searchConsultantName", ViewBag.CurrentFilterConsultantName as string) - Find by Consultant Name
    </p>
    <p>
        @Html.TextBox("searchConsultantLastName", ViewBag.CurrentFilterConsultantLastName as string) - Find by Consultant Last Name
    </p>
    <p>
        @Html.TextBox("searchConsultantPersonalid", ViewBag.CurrentFilterConsultantPersonalId as long?) - Find by  Consultant Personal Id
    </p>
    <p>
        @Html.TextBox("searchConsultantBirthDate", ViewBag.CurrentFilterConsultantBirthDate as DateTime?, new { type = "date" }) - Find by Birth Date
    </p>
    <p>
        @Html.TextBox("searchAmount", ViewBag.CurrentFilterAmount as int?) - Find by Amount
    </p>
    <p>
        @Html.TextBox("searchHierarchyAmount", ViewBag.CurrentFilterHierarchyAmount as int?) - Find by Hierarchy Amount
    </p>
    <input type="submit" value="Filter" />
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("ConsultantId", "GetConsultantsSalesCount", new
            {
                sortOrder = ViewBag.ConsultantIdSortParam,
                searchConsultantName = ViewBag.CurrentFilterConsultantName,
                searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
                searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
                searchAmount = ViewBag.CurrentFilterAmount,
                searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
                startDate = ViewBag.SearchParameterStartDate,
                endDate = ViewBag.SearchParameterEndDate
            })
        </th>
        <th>
            @Html.ActionLink("ConsultantName", "GetConsultantsSalesCount", new { sortOrder = ViewBag.ConsultantNameSortParam,
           searchConsultantName = ViewBag.CurrentFilterConsultantName,
           searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
           searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
           searchAmount = ViewBag.CurrentFilterAmount,
           searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
           startDate = ViewBag.SearchParameterStartDate,
           endDate = ViewBag.SearchParameterEndDate
       })
        </th>
        <th>
            @Html.ActionLink("ConsultantLastName", "GetConsultantsSalesCount", new { sortOrder = ViewBag.ConsultantLastNameSortParam ,
           searchConsultantName = ViewBag.CurrentFilterConsultantName,
           searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
           searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
           searchAmount = ViewBag.CurrentFilterAmount,
           searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
           startDate = ViewBag.SearchParameterStartDate,
           endDate = ViewBag.SearchParameterEndDate
       })
        </th>
        <th>
            @Html.ActionLink("ConsultantPersonalId", "GetConsultantsSalesCount", new { sortOrder = ViewBag.ConsultantPersonalIdSortParam,
           searchConsultantName = ViewBag.CurrentFilterConsultantName,
           searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
           searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
           searchAmount = ViewBag.CurrentFilterAmount,
           searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
           startDate = ViewBag.SearchParameterStartDate,
           endDate = ViewBag.SearchParameterEndDate
       })
        </th>
        <th>
            @Html.ActionLink("BirthDate", "GetConsultantsSalesCount", new
       {
           sortOrder = ViewBag.BirthDateSortParam,
           searchConsultantName = ViewBag.CurrentFilterConsultantName,
           searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
           searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
           searchAmount = ViewBag.CurrentFilterAmount,
           searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
           startDate = ViewBag.SearchParameterStartDate,
           endDate = ViewBag.SearchParameterEndDate
       })
        </th>
        <th>
            @Html.ActionLink("SalesAmount", "GetConsultantsSalesCount", new { sortOrder = ViewBag.AmountSortParam,
           searchConsultantName = ViewBag.CurrentFilterConsultantName,
           searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
           searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
           searchAmount = ViewBag.CurrentFilterAmount,
           searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
           startDate = ViewBag.SearchParameterStartDate,
           endDate = ViewBag.SearchParameterEndDate
       })
        </th>
        <th>
            @Html.ActionLink("HierarchySalesAmount", "GetConsultantsSalesCount", new
       {
           sortOrder = ViewBag.HierarchySalesAmountSortParam,
           searchConsultantName = ViewBag.CurrentFilterConsultantName,
           searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
           searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
           searchAmount = ViewBag.CurrentFilterAmount,
           searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
           startDate = ViewBag.SearchParameterStartDate,
           endDate = ViewBag.SearchParameterEndDate
       })
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsultantId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsultantName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsultantLastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsultantPersonalId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsultantBirthDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SalesAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HierarchySalesAmount)
                </td>
                <td>
            </tr>
        }
    }

</table>

@Html.PagedListPager(Model, page => Url.Action("GetConsultantsSalesCount", "SaleDetailSearch",
    new
    {
        sortOrder = ViewBag.CurrentSort,
        searchConsultantName = ViewBag.CurrentFilterConsultantName,
        searchConsultantLastName = ViewBag.CurrentFilterConsultantLastName,
        searchConsultantBirthDate = ViewBag.CurrentFilterConsultantBirthDate,
        searchAmount = ViewBag.CurrentFilterAmount,
        searchHierarchyAmount = ViewBag.CurrentFilterHierarchyAmount,
        startDate = ViewBag.SearchParameterStartDate,
        endDate = ViewBag.SearchParameterEndDate,
        page
    }))

BOG/Views/SaleDetailSearch/Index.cshtml
@model IEnumerable<BOG.Models.SearchModels.SaleInfoByProductPrice>

@{
    ViewBag.Title = "Index";
}

<nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("GetSaleInfoByConsultant I", "GetSaleInfoByConsultant", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetSaleInfoByProductPrice II", "GetSaleInfoByProductPrice", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetFrequentlySaledProducts III", "GetFrequentlySaledProducts", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetConsultantsSalesCount IV", "GetConsultantsSalesCount", "SaleDetailSearch")</li>
        <li>@Html.ActionLink("GetProfitableProducts V", "GetProfitableProducts", "SaleDetailSearch")</li>
    </ul>
</nav>