BOG/Models/Consultant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BOG.Models
{
    public class Consultant
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string LastName { get; set; }

        [Index("Consultants_Personal_Id_Unique", 1, IsUnique = true)]
        public long PersonalId { get; set; }

        public Gender Gender { get; set; }

        public DateTime BirthDate { get; set; }

        public int? RecomendatorId { get; set; }

        public List<Sale> Sales { get; set; }
    }
}

BOG/Controllers/SalesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BOG.Constants.Filtering;
using BOG.Constants.Paging;
using BOG.DAL.Implementation;
using BOG.Helper;
using BOG.Models;
using PagedList;

namespace BOG.Controllers
{
    public class SalesController : Controller
    {
        private readonly Bog _db = new Bog();

        // GET: Sales
        public ActionResult Index(string sortOrder, int? searchId, string searchName, string searchLastName, int? searchConsultantId, DateTime? searchCreatedAt, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentFilterId = searchId;
            ViewBag.CurrentFilterName = searchName;
            ViewBag.CurrentFilterLastName = searchLastName;
            ViewBag.CurrentFilterConsultantId = searchConsultantId;
            ViewBag.CurrentFilterCreatedAt = searchCreatedAt;
            ViewBag.IdSortParam = string.IsNullOrEmpty(sortOrder) ? FilteringNames.IdDesc : "";
            ViewBag.NameSortParam = sortOrder == FilteringNames.Name ? FilteringNames.NameDesc : FilteringNames.Name;
            ViewBag.LastNameSortParam = sortOrder == FilteringNames.LastName ? FilteringNames.LastNameDesc : FilteringNames.LastName;
            ViewBag.CreatedAtSortParam = sortOrder == FilteringNames.CreatedAt ? FilteringNames.CreatedAtDesc : FilteringNames.CreatedAt;
            ViewBag.ConsultantIdSortParam = sortOrder == FilteringNames.ConsultantId ? FilteringNames.ConsultantIdDesc : FilteringNames.ConsultantId;
            var sales = _db.Sales.ToList();
            if (searchId.HasValue)
            {
                sales = sales.Where(s => s.Id == searchId).ToList();
            }
            if (!string.IsNullOrEmpty(searchName))
            {
                sales = sales.Where(s => s.Consultant.Name.Contains(searchName)).ToList();
            }
            if (!string.IsNullOrEmpty(searchLastName))
            {
                sales = sales.Where(s => s.Consultant.LastName.Contains(searchLastName)).ToList();
            }
            if (searchConsultantId.HasValue)
            {
                sales = sales.Where(s => s.ConsultantId == searchConsultantId.Value).ToList();
            }
            if (searchCreatedAt != null)
            {
                sales = sales.Where(s => s.CreatedAt.Day == searchCreatedAt.Value.Day
                                                     && s.CreatedAt.Month == searchCreatedAt.Value.Month
                                                     && s.CreatedAt.Year == searchCreatedAt.Value.Year).ToList();
            }
            switch (sortOrder)
            {
                case FilteringNames.IdDesc:
                    sales = sales.OrderByDescending(s => s.Id).ToList();
                    break;
                case FilteringNames.LastNameDesc:
                    sales = sales.OrderByDescending(s => s.Consultant.LastName).ToList();
                    break;
                case FilteringNames.NameDesc:
                    sales = sales.OrderByDescending(s => s.Consultant.Name).ToList();
                    break;
                case FilteringNames.ConsultantIdDesc:
                    sales = sales.OrderByDescending(s => s.ConsultantId).ToList();
                    break;
                case FilteringNames.CreatedAtDesc:
                    sales = sales.OrderByDescending(s => s.CreatedAt).ToList();
                    break;
                case FilteringNames.Name:
                    sales = sales.OrderBy(s => s.Consultant.Name).ToList();
                    break;
                case FilteringNames.LastName:
                    sales = sales.OrderBy(s => s.Consultant.LastName).ToList();
                    break;
                case FilteringNames.CreatedAt:
                    sales = sales.OrderBy(s => s.CreatedAt).ToList();
                    break;
                case FilteringNames.ConsultantId:
                    sales = sales.OrderBy(s => s.ConsultantId).ToList();
                    break;
                default:
                    sales = sales.OrderBy(s => s.Id).ToList();
                    break;
            }
            var pagedData = sales.ToPagedList(PageFormatter.GetValidPage(page), Paging.PageSize);
            if (!pagedData.Any() && PageFormatter.GetValidPage(page) != 1)
            {
                return View(sales.ToPagedList(1, Paging.PageSize));
            }
            return View(pagedData);
        }

        // GET: Sales/Details/5
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sale = await _db.Sales.FindAsync(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            sale.SaleDetails = _db.SaleDetails.Where(x => x.SaleId == id.Value).ToList();
            return View(sale);
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            ViewBag.ConsultantIds = _db.Consultants.ToListAsync().Result;
            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,ConsultantId,CreatedAt")] Sale sale)
        {
            if (!ModelState.IsValid)
            {
                return View(sale);
            }
            sale.CreatedAt = DateTime.Now;
            _db.Sales.Add(sale);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Sales/Edit/5
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sale = await _db.Sales.FindAsync(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,ConsultantId,CreatedAt")] Sale sale)
        {
            if (!ModelState.IsValid)
            {
                return View(sale);
            }
            _db.Entry(sale).State = EntityState.Modified;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Sales/Delete/5
        public async Task<ActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var sale = await _db.Sales.FindAsync(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id)
        {
            _db.Sales.Remove(await _db.Sales.FindAsync(id) ?? throw new InvalidOperationException());
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BOG/Views/Consultants/Create.cshtml
@model BOG.Models.Consultant

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Consultant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonalId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecomendatorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecomendatorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecomendatorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BOG/Views/Consultants/Delete.cshtml
@model BOG.Models.Consultant

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consultant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecomendatorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecomendatorId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BOG/Views/Consultants/Details.cshtml
@model BOG.Models.Consultant

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Consultant</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecomendatorId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecomendatorId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<table class="table">
    @if (Model.Sales.Count > 0)
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => Model.Sales.First().Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => Model.Sales.First().CreatedAt)
            </th>
            <th></th>
        </tr>
    }

    @foreach (var item in Model.Sales)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Sales", new { id = item.Id }, null) |
                @Html.ActionLink("Details", "Details", "Sales", new { id = item.Id }, null) |
                @Html.ActionLink("Delete", "Delete", "Sales", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>

BOG/Views/Consultants/Edit.cshtml
@model BOG.Models.Consultant

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Consultant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonalId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonalId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonalId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecomendatorId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecomendatorId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecomendatorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BOG/Views/Consultants/Index.cshtml
@model PagedList.IPagedList<BOG.Models.Consultant>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}
<br>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        @Html.TextBox("searchId", ViewBag.CurrentFilterId as int?) - Find by Id
    </p>
    <p>
        @Html.TextBox("searchName", ViewBag.CurrentFilterName as string) - Find by Name
    </p>
    <p>
        @Html.TextBox("searchLastName", ViewBag.CurrentFilterLastName as string) - Find by Last Name
    </p>
    <p>
        @Html.TextBox("SearchPersonalId", ViewBag.CurrentFilterPersonalId as long?) - Find by Personal Id
    </p>
    <p>
        @Html.TextBox("SearchRecomendatorId", ViewBag.CurrentFilterRecomendatorId as int?) - Find by Recomendator Id
    </p>
    <p>
        @Html.TextBox("SearchBirthDate", ViewBag.CurrentFilterBirthDate as DateTime?) - Find by Birth Date
    </p>
    <input type="submit" value="Filter" />
}
<br>
@using (Html.BeginForm())
{
    <input type="submit" value="Reset" />
}

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Id", "Index", new { sortOrder = ViewBag.IdSortParam })
        </th>
        <th>
            @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParam })
        </th>
        <th>
            @Html.ActionLink("LastName", "Index", new { sortOrder = ViewBag.LastNameSortParam })
        </th>
        <th>
            @Html.ActionLink("PersonalId", "Index", new { sortOrder = ViewBag.PersonalIdSortParam })
        </th>
        <th>
            @Html.ActionLink("Gender", "Index", new { sortOrder = ViewBag.GenderSortParam })
        </th>
        <th>
            @Html.ActionLink("BirthDate", "Index", new { sortOrder = ViewBag.BirthDateSortParam })
        </th>
        <th>
            @Html.ActionLink("RecomendatorId", "Index", new { sortOrder = ViewBag.RecomendatorIdSortParam })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonalId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecomendatorId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

    @Html.PagedListPager(Model, page => Url.Action("Index",
                    new
                    {
                        sortOrder = ViewBag.CurrentSort,
                        searchName = ViewBag.CurrentFilterName,
                        searchLastName = ViewBag.CurrentFilterLastName,
                        searchRecomendatorId = ViewBag.CurrentFilterRecomendatorId,
                        searchBirthDate = ViewBag.CurrentFilterBirthDate,
                        page
                    }))